// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/atelier" | "/checkout/[slug]" | "/checkout/thank-you" | "/collections" | "/collections/[category]" | "/collections/[category]/[productId]" | "/collections/fine-jewelry" | "/diamond-earrings" | "/diamond-necklaces" | "/diamond-rings" | "/diamonds" | "/engagement-rings" | "/high-jewelry" | "/inquiry" | "/items-to-order" | "/mens-jewelry" | "/mirror" | "/products" | "/products/[slug]" | "/signature" | "/tennis-bracelets" | "/wedding-rings"
type AppRouteHandlerRoutes = "/api/atelier/proxy-image" | "/api/atelier/render"
type PageRoutes = never
type LayoutRoutes = "/" | "/collections/[category]" | "/collections/[category]/[productId]" | "/inquiry" | "/mirror"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/atelier/proxy-image": {}
  "/api/atelier/render": {}
  "/atelier": {}
  "/checkout/[slug]": { "slug": string; }
  "/checkout/thank-you": {}
  "/collections": {}
  "/collections/[category]": { "category": string; }
  "/collections/[category]/[productId]": { "category": string; "productId": string; }
  "/collections/fine-jewelry": {}
  "/diamond-earrings": {}
  "/diamond-necklaces": {}
  "/diamond-rings": {}
  "/diamonds": {}
  "/engagement-rings": {}
  "/high-jewelry": {}
  "/inquiry": {}
  "/items-to-order": {}
  "/mens-jewelry": {}
  "/mirror": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/signature": {}
  "/tennis-bracelets": {}
  "/wedding-rings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/collections/[category]": never
  "/collections/[category]/[productId]": never
  "/inquiry": never
  "/mirror": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
