// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/atelier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/atelier">> = Specific
  const handler = {} as typeof import("../../app/atelier/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/[slug]">> = Specific
  const handler = {} as typeof import("../../app/checkout/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/thank-you/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/thank-you">> = Specific
  const handler = {} as typeof import("../../app/checkout/thank-you/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/collections/[category]/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/[category]/[productId]">> = Specific
  const handler = {} as typeof import("../../app/collections/[category]/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/collections/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/[category]">> = Specific
  const handler = {} as typeof import("../../app/collections/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/collections/fine-jewelry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections/fine-jewelry">> = Specific
  const handler = {} as typeof import("../../app/collections/fine-jewelry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections">> = Specific
  const handler = {} as typeof import("../../app/collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/diamond-earrings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diamond-earrings">> = Specific
  const handler = {} as typeof import("../../app/diamond-earrings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/diamond-necklaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diamond-necklaces">> = Specific
  const handler = {} as typeof import("../../app/diamond-necklaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/diamond-rings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diamond-rings">> = Specific
  const handler = {} as typeof import("../../app/diamond-rings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/diamonds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/diamonds">> = Specific
  const handler = {} as typeof import("../../app/diamonds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engagement-rings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagement-rings">> = Specific
  const handler = {} as typeof import("../../app/engagement-rings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/high-jewelry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/high-jewelry">> = Specific
  const handler = {} as typeof import("../../app/high-jewelry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inquiry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inquiry">> = Specific
  const handler = {} as typeof import("../../app/inquiry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/items-to-order/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/items-to-order">> = Specific
  const handler = {} as typeof import("../../app/items-to-order/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mens-jewelry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mens-jewelry">> = Specific
  const handler = {} as typeof import("../../app/mens-jewelry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mirror/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mirror">> = Specific
  const handler = {} as typeof import("../../app/mirror/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[slug]">> = Specific
  const handler = {} as typeof import("../../app/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signature/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signature">> = Specific
  const handler = {} as typeof import("../../app/signature/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tennis-bracelets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tennis-bracelets">> = Specific
  const handler = {} as typeof import("../../app/tennis-bracelets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wedding-rings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wedding-rings">> = Specific
  const handler = {} as typeof import("../../app/wedding-rings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/atelier/proxy-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/atelier/proxy-image">> = Specific
  const handler = {} as typeof import("../../app/api/atelier/proxy-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/atelier/render/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/atelier/render">> = Specific
  const handler = {} as typeof import("../../app/api/atelier/render/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/collections/[category]/[productId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/collections/[category]/[productId]">> = Specific
  const handler = {} as typeof import("../../app/collections/[category]/[productId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/collections/[category]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/collections/[category]">> = Specific
  const handler = {} as typeof import("../../app/collections/[category]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inquiry/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/inquiry">> = Specific
  const handler = {} as typeof import("../../app/inquiry/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mirror/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/mirror">> = Specific
  const handler = {} as typeof import("../../app/mirror/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
